### ISSUE TITLE
Fix two failing tests on Travis CI

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-media#201]
Two tests are passing locally but failing in Travis. I temporarily marked them to be skipped (https://github.com/evercam/evercam-media/pull/200/commits/85094f42dca69d371044bbffe0d26c24025f800a) but we should fix this.

This is the output of the failing tests:

```
  1) test GET /v1/cameras/:id/thumbnail (EvercamMedia.CameraControllerTest)
     test/controllers/camera_controller_test.exs:31
     ** (Ecto.ConstraintError) constraint error when attempting to insert struct:
     
         * foreign_key: snapshots_camera_id_fkey1
     
     If you would like to convert this constraint into an error, please
     call foreign_key_constraint/3 in your changeset and define the proper
     constraint name. The changeset defined the following constraints:
     
         * unique: snapshots_pkey
     
     stacktrace:
       (ecto) lib/ecto/repo/schema.ex:390: anonymous fn/5 in Ecto.Repo.Schema.constraints_to_errors/3
       (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ecto) lib/ecto/repo/schema.ex:183: anonymous fn/11 in Ecto.Repo.Schema.do_insert/4
       (ecto) lib/ecto/repo/schema.ex:570: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
       (ecto) lib/ecto/adapters/sql.ex:434: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
       (db_connection) lib/db_connection.ex:1079: DBConnection.transaction_run/4
       (db_connection) lib/db_connection.ex:1009: DBConnection.run_begin/3
       (db_connection) lib/db_connection.ex:766: DBConnection.transaction/3
       test/controllers/camera_controller_test.exs:24: EvercamMedia.CameraControllerTest.__ex_unit_setup_1/1
       test/controllers/camera_controller_test.exs:1: EvercamMedia.CameraControllerTest.__ex_unit__/2

  2) test lists ranges of expired snapshots (SnapshotTest)
     test/models/snapshot_test.exs:64
     ** (Ecto.ConstraintError) constraint error when attempting to insert struct:
     
         * foreign_key: snapshots_camera_id_fkey1
     
     If you would like to convert this constraint into an error, please
     call foreign_key_constraint/3 in your changeset and define the proper
     constraint name. The changeset has not defined any constraint.
     
     stacktrace:
       (ecto) lib/ecto/repo/schema.ex:390: anonymous fn/5 in Ecto.Repo.Schema.constraints_to_errors/3
       (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ecto) lib/ecto/repo/schema.ex:183: anonymous fn/11 in Ecto.Repo.Schema.do_insert/4
       (ecto) lib/ecto/repo/schema.ex:570: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
       (ecto) lib/ecto/adapters/sql.ex:434: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
       (db_connection) lib/db_connection.ex:1079: DBConnection.transaction_run/4
       (db_connection) lib/db_connection.ex:1009: DBConnection.run_begin/3
       (db_connection) lib/db_connection.ex:766: DBConnection.transaction/3
       (ecto) lib/ecto/repo/schema.ex:108: Ecto.Repo.Schema.insert!/4
       test/models/snapshot_test.exs:45: SnapshotTest.__ex_unit_setup_1/1
       test/models/snapshot_test.exs:1: SnapshotTest.__ex_unit__/2
```

**Comment by mosic** [comment]
This was fixed, closing.
