### ISSUE TITLE
Handle PTZ requests to cameras which don't support it

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-media#233]
Right now such request fails with 500 error, it would be nice if it was more user-friendly. An example from the logs:

```
[error] Error invoking GetPresets.

URL: http://{...}/onvif/PTZ

auth: {...}:{...}.

Request:
"<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope"
xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"
xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis=200401-wss-wssecurity-utility-1.0.xsd">
<SOAP-ENV:Header><wsse:Security><wsse:UsernameToken>
<wsse:Username>{...}</wsse:Username>
<wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">{...}</wsse:Password>
<wsse:Nonce>{...}</wsse:Nonce>
<wsu:Created>2016-05-24T15:13:04Z</wsu:Created></wsse:UsernameToken>
</wsse:Security></SOAP-ENV:Header><SOAP-ENV:Body>
<tptz:GetPresets xmlns:tptz="http://www.onvif.org/ver20/ptz/wsdl"><ProfileToken>Profile_1</ProfileToken></tptz:GetPresets>
</SOAP-ENV:Body></SOAP-ENV:Envelope>".

Response %HTTPotion.Response{body: "
<?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:soapenc="http://www.w3.org/2003/05/soap-encoding" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tt="http://www.onvif.org/ver10/schema" xmlns:tds="http://www.onvif.org/ver10/device/wsdl" xmlns:trt="http://www.onvif.org/ver10/media/wsdl" xmlns:timg="http://www.onvif.org/ver20/imaging/wsdl" xmlns:tev="http://www.onvif.org/ver10/events/wsdl" xmlns:tptz="http://www.onvif.org/ver20/ptz/wsdl" xmlns:tan="http://www.onvif.org/ver20/analytics/wsdl" xmlns:tst="http://www.onvif.org/ver10/storage/wsdl" xmlns:ter="http://www.onvif.org/ver10/error" xmlns:dn="http://www.onvif.org/ver10/network/wsdl" xmlns:tns1="http://www.onvif.org/ver10/topics" xmlns:tmd="http://www.onvif.org/ver10/deviceIO/wsdl" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl" xmlns:wsoap12="http://schemas.xmlsoap.org/wsdl/soap12" xmlns:http="http://schemas.xmlsoap.org/wsdl/http" xmlns:d="http://schemas.xmlsoap.org/ws/2005/04/discovery" xmlns:wsadis="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:xop="http://www.w3.org/2004/08/xop/include" xmlns:wsnt="http://docs.oasis-open.org/wsn/b-2" xmlns:wsa="http://www.w3.org/2005/08/addressing" xmlns:wstop="http://docs.oasis-open.org/wsn/t-1" xmlns:wsrf-bf="http://docs.oasis-open.org/wsrf/bf-2" xmlns:wsntw="http://docs.oasis-open.org/wsn/bw-2" xmlns:wsrf-rw="http://docs.oasis-open.org/wsrf/rw-2" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsrf-r="http://docs.oasis-open.org/wsrf/r-2" xmlns:trc="http://www.onvif.org/ver10/recording/wsdl" xmlns:tse="http://www.onvif.org/ver10/search/wsdl" xmlns:trp="http://www.onvif.org/ver10/replay/wsdl" xmlns:tnshik="http://www.hikvision.com/2011/event/topics" xmlns:hikwsd="http://www.onvifext.com/onvif/ext/ver10/wsdl" xmlns:hikxsd="http://www.onvifext.com/onvif/ext/ver10/schema"><env:Body><env:Fault><env:Code><env:Value>env:Receiver</env:Value>
<env:Subcode><env:Value>ter:ActionNotSupported</env:Value>
<env:Subcode><env:Value>ter:PTZNotSupported</env:Value>
</env:Subcode>
</env:Subcode>
</env:Code>
<env:Reason><env:Text xml:lang="en">PTZ is not supported..</env:Text>
</env:Reason>
<env:Node>http://www.w3.org/2003/05/soap-envelope/node/ultimateReceiver</env:Node>
<env:Role>http://www.w3.org/2003/05/soap-envelope/role/ultimateReceiver</env:Role>
<env:Detail><env:Text>PTZ is not supported by the device.</env:Text>
</env:Detail>
</env:Fault>
</env:Body>
</env:Envelope>
",
headers: [Connection: "close", "Content-Length": "2540", "Content-Type": "application/soap+xml; charset=utf-8", Date: "Sun, 23 Aug 2015 10:14:02 GMT", Server: "App-webs/"], status_code: 500}.


[error] #PID<0.23792.14> running EvercamMedia.Endpoint terminated
Request: GET /v1/cameras/{...}/ptz/presets?api_id={...}&api_key={...}
** (exit) an exception was raised:
** (MatchError) no match of right hand side value: {:error, 500, %{"Fault" => %{"Code" => %{"Subcode" => %{"Subcode" => %{"Value" => "ter:PTZNotSupported"}, "Value" => "ter:ActionNotSupported"}, "Value" => "env:Receiver"}, "Detail" => %{"Text" => "PTZ is not supported by the device."}, "Node" => "http://www.w3.org/2003/05/soap-envelope/node/ultimateReceiver", "Reason" => %{"Text" => "PTZ is not supported.."}, "Role" => "http://www.w3.org/2003/05/soap-envelope/role/ultimateReceiver"}}}
(evercam_media) lib/evercam_media/onvif/onvif_ptz.ex:14: EvercamMedia.ONVIFPTZ.get_presets/2
(evercam_media) web/controllers/onvifptz_controller.ex:21: EvercamMedia.ONVIFPTZController.presets/2
(evercam_media) web/controllers/onvifptz_controller.ex:1: EvercamMedia.ONVIFPTZController.action/2
(evercam_media) web/controllers/onvifptz_controller.ex:1: EvercamMedia.ONVIFPTZController.phoenix_controller_pipeline/2
(evercam_media) lib/phoenix/router.ex:261: EvercamMedia.Router.dispatch/2
(evercam_media) web/router.ex:1: EvercamMedia.Router.do_call/2
(evercam_media) lib/evercam_media/endpoint.ex:1: EvercamMedia.Endpoint.phoenix_pipeline/1
(evercam_media) lib/phoenix/endpoint/render_errors.ex:34: EvercamMedia.Endpoint.call/2
```

**Comment by marcoherbst** [comment]
Hi @jgarciasacristan  this problem raised it's head again today. ... what are your thoughts? Is it a biggie?
M

**Comment by marcoherbst** [comment]
https://dash.evercam.io/v1/cameras/hikvis-dmo/details ... is PTZ but isn't working (slightly different to what Milos described) ... but basically the same issue.

**Comment by jgarciasacristan** [comment]
The original problem that Milos describes is not biggie. It is simply that
https://github.com/evercam/evercam-media/blob/master/lib/evercam_media/onvif/onvif_ptz.ex#L12
does not handle the error tuple! :-(  . I have already sorted out that
problem in
https://github.com/evercam/evercam-media/blob/master/web/controllers/onvif_controller.ex
. So same should be applied to the old PTZ methods.  I'll create a PR
fixing the issue this week.
Regarding https://dash.evercam.io/v1/cameras/hikvis-dmo/details I'll give
it a try once I fixed it the error handling issue.

I've been very busy for the last couple of weeks, but hopefully our release
 is out today. Need to get back to my elixir nights. Thanks for pinging me.

**Comment by ijunaid8088** [comment]
its already done!
